import cake1 from "../assets/cakes/buttercream1.svg";
import cake2 from "../assets/cakes/buttercream2.svg";
import cake3 from "../assets/cakes/buttercream3.svg";
import cake4 from "../assets/cakes/buttercream4.svg";
import cake5 from "../assets/cakes/buttercream5.svg";
import cake6 from "../assets/cakes/buttercream6.svg";
import cake7 from "../assets/cakes/buttercream7.svg";
import cake8 from "../assets/cakes/buttercream8.svg";
import cake9 from "../assets/cakes/buttercream9.svg";
import cake10 from "../assets/cakes/buttercream10.svg";
import CakeIcon from "../assets/icons/cake-icon.svg";
import TickIcon from "../assets/icons/tick-circle.svg";
import BicycleIcon from "../assets/icons/bicycle.svg";

export const data = [
  {
    category: "Buttercream Cakes",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Fondant cake",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Whipped cream cake",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Pastries",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Cake slices",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Cupcakes",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Cake parfait",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Foil cake",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Small chops",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
];

export const details = [
  {
    title: "Fresh cake",
    description:
      "We are passionate about baking. Each of our handmade products are carefully baked with love.",
    icon: CakeIcon,
  },
  {
    title: "BEST PRODUCTS",
    description:
      "All our ingredients are made with the finest quality ingredients and guranteed fresh.",
    icon: TickIcon,
  },
  {
    title: "Fast delivery",
    description:
      "Enjoy the convenience of swift and reliable cake delivery with our brand.",
    icon: BicycleIcon,
  },
];
