import cake1 from "../assets/cakes/buttercream1.svg";
import cake2 from "../assets/cakes/buttercream2.svg";
import cake3 from "../assets/cakes/buttercream3.svg";
import cake4 from "../assets/cakes/buttercream4.svg";
import cake5 from "../assets/cakes/buttercream5.svg";
import cake6 from "../assets/cakes/buttercream6.svg";
import cake7 from "../assets/cakes/buttercream7.svg";
import cake8 from "../assets/cakes/buttercream8.svg";
import cake9 from "../assets/cakes/buttercream9.svg";
import cake10 from "../assets/cakes/buttercream10.svg";
import { BicycleIcon, CakeIcon, TickCircleIcon } from "../assets/icons/Icons";

export const data2 = [
  {
    category: "Buttercream Cakes",
    items: {
      cake1: {
        id: "010",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        id: "011",
        type: "7’ Stencil Buttercream Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        id: "012",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        id: "013",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        id: "014",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        id: "015",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        id: "016",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        id: "017",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        id: "018",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        id: "019",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Fondant cake",
    items: {
      cake1: {
        id: "020",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        id: "021",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Whipped cream cake",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Pastries",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Cake slices",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Cup cakes",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Cake parfait",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Foil cake",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Small chops",
    items: {
      cake1: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
];
export const data = [
  {
    category: "Buttercream Cakes",
    items: {
      cake1: {
        id: "010",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        id: "011",
        type: "7’ Stencil Buttercream Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        id: "012",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        id: "013",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        id: "014",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        id: "015",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        id: "016",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        id: "017",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        id: "018",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        id: "019",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
  {
    category: "Fondant cake",
    items: {
      cake1: {
        id: "020",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        id: "021",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        id: "022",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        id: "023",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        id: "024",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        id: "025",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        id: "026",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        id: "027",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        id: "028",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        id: "029",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },

  {
    category: "Whipped cream cake",
    items: {
      cake1: {
        id: "030",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        id: "031",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        id: "032",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        id: "033",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        id: "034",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        id: "035",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        id: "036",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        id: "037",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        id: "038",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        id: "039",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },

  {
    category: "Pastries",
    items: {
      cake1: {
        id: "040",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        id: "041",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        id: "042",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        id: "043",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        id: "044",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        id: "045",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        id: "046",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        id: "047",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        id: "048",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        id: "049",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },

  {
    category: "Cake slices",
    items: {
      cake1: {
        id: "050",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        id: "051",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        id: "052",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        id: "053",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        id: "054",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        id: "055",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        id: "056",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        id: "057",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        id: "058",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        id: "059",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },

  {
    category: "Cup cakes",
    items: {
      cake1: {
        id: "060",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        id: "061",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        id: "062",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        id: "063",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        id: "064",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        id: "065",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        id: "066",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        id: "067",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        id: "068",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        id: "069",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },

  {
    category: "Cake parfait",
    items: {
      cake1: {
        id: "070",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        id: "071",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        id: "072",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        id: "073",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        id: "074",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        id: "075",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        id: "076",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        id: "077",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        id: "078",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        id: "079",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },

  {
    category: "Foil cake",
    items: {
      cake1: {
        id: "080",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        id: "081",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        id: "082",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        id: "083",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        id: "084",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        id: "085",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        id: "086",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        id: "087",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        id: "088",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        id: "089",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },

  {
    category: "Small chops",
    items: {
      cake1: {
        id: "090",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake1,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake2: {
        id: "091",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake2,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake3: {
        id: "092",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake3,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake4: {
        id: "093",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake4,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake5: {
        id: "094",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake5,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake6: {
        id: "095",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake6,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake7: {
        id: "096",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake7,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake8: {
        id: "097",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake8,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake9: {
        id: "098",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake9,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
      cake10: {
        id: "099",
        type: "8’ Drip Chocolate Cake",
        price: 15000,
        image: cake10,
        description: {
          "Cake flavours": "Vanilla & Chocolate",
          "Cake size": "8inches",
          "Icing type": "Buttercream",
          Colour: "Pink",
          "Preparation and delivery": "5hours",
        },
      },
    },
  },
];

export const details = [
  {
    title: "Fresh cake",
    description:
      "We are passionate about baking. Each of our handmade products are carefully baked with love.",
    icon: <CakeIcon />,
  },
  {
    title: "BEST PRODUCTS",
    description:
      "All our ingredients are made with the finest quality ingredients and guranteed fresh.",
    icon: <TickCircleIcon />,
  },
  {
    title: "Fast delivery",
    description:
      "Enjoy the convenience of swift and reliable cake delivery with our brand.",
    icon: <BicycleIcon />,
  },
];
export const reviews = [
  {
    id: "001",
    date: "2 weeks ago",
    title: "Fresh cake",
    comment:
      "The cake and doughnuts i ordered looks really nice and taste yummy.The delivery service is top notch too.",
    icon: "⭐️⭐️⭐️⭐️⭐️",
    user: "Grace Akintola",
  },
  {
    id: "002",
    date: "2 weeks ago",
    title: "Fresh cake",
    comment:
      "The cake and doughnuts i ordered looks really nice and taste yummy.The delivery service is top notch too.",
    icon: "⭐️⭐️⭐️⭐️⭐️",
    user: "Grace Akintola",
  },
  {
    id: "003",
    date: "2 weeks ago",
    title: "Fresh cake",
    comment:
      "The cake and doughnuts i ordered looks really nice and taste yummy.The delivery service is top notch too.",
    icon: "⭐️⭐️⭐️⭐️⭐️",
    user: "Grace Akintola",
  },
  {
    id: "004",
    date: "2 weeks ago",
    title: "Fresh cake",
    comment:
      "The cake and doughnuts i ordered looks really nice and taste yummy.The delivery service is top notch too.",
    icon: "⭐️⭐️⭐️⭐️⭐️",
    user: "Grace Akintola",
  },
];

export const footer = [
  {
    title: "Menu",
    data: ["Home", "Category", "Account"],
  },
  {
    title: "Quick links",
    data: ["About us", "FAQs", "Reviews", "Terms & conditions"],
  },
];

export const review = [
  {
    id: "001",
    title: "Impressed",
    comment:
      "I am highly impressed. No cake shop is going to eat my money again. Customer service, punctuality , attention to details….They outdid themselves",
    user: "Adedeji Bashirat",
    rate: 5,
    date: "2 days ago",
  },
  {
    id: "200",
    title: "Amazing",
    comment:
      "The cake taste nice, packaging and delivery was top notch too. I like the way i could customize my order to my preference. Keep it up ",
    user: "Funmi Awe",
    rate: 5,
    date: "2 days ago",
  },
  {
    id: "301",
    title: "Good customer service",
    comment:
      "Good customer service and prompt delivery. Always at peace whenever I place an order because there’s confidence in service delivery. The cake is beautiful and yummy ( trying to get the best adjective to describe the cake)",
    user: "Mathew",
    rate: 5,
    date: "2 days ago",
  },
];
